Repository dknowles2/pydrawise, pull requests merged in 2023-12, with the labels that each got.

#103 Use the raw GraphQL schema instead of one generated from our models
  pydrawise/client.py
  pydrawise/hydrawise.graphql
  pydrawise/schema.py
  pydrawise/schema_utils.py
Labels: cleanup

#100 Add support for sensors and water flow summary.
  pydrawise/client.py
  tests/test_client.py
Labels: enhancement

#101 Add support for watering reports.
  pydrawise/client.py
  pydrawise/schema.py
  tests/test_client.py
Labels: enhancement

#111 Fix a NPE bug.
  pydrawise/client.py
  tests/test_client.py
Labels: bug

#112 Fix watering report bug
  pydrawise/client.py
  tests/test_client.py
Labels: bug
